//promise
// let p = new Promise((resolve, reject) => {
//     let a = -3 + 5;
//     if(a === 2){
//         resolve('Success')
//     }else{
//         reject('Failed the calculation')
//     }
// });

// p.then((message) => {
//     console.log(message);
// })
//     .catch((error) => {
//     console.log(error);
// });

